# Generated by Django 5.2.1 on 2025-05-16 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('hist', 'Гистограмма'), ('scatter', 'Точечный график'), ('line', 'Линейный график'), ('bar', 'Столбчатая диаграмма'), ('pie', 'Круговая диаграмма')], max_length=20)),
                ('x_column', models.CharField(max_length=100)),
                ('y_column', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='analysis_results/')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.dataset')),
            ],
        ),
    ]
